/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the groovy plugin to also add support for Groovy (needed for Spock)
    java
    id("me.champeau.jmh") version "0.7.1"
}

configurations {
    jmhImplementation {
        extendsFrom(configurations.implementation.get())
        configurations.findByName("platformImplementation")?.let {
            extendsFrom(it)
        }
    }
    jmhRuntimeClasspath {
        attributes {
            attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(LibraryElements.JAR))
        }
    }
}

jmh {
    includeTests = false
    resultFormat = "CSV"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    jmhImplementation("com.google.guava:guava:31.1-jre")

    jmhImplementation("commons-io:commons-io:2.13.0")

    jmhImplementation("org.apache.httpcomponents:httpclient:4.5.14")
    jmhImplementation("org.apache.httpcomponents:httpasyncclient:4.1.5")

    jmhImplementation("org.apache.httpcomponents.client5:httpclient5:5.2.1")
}
